---

- name: Fetch release
  fetch:
    src: "{{ project_path }}/rel/{{ app_name }}/releases/{{ app_version }}/{{ app_name }}.tar.gz"
    dest: "{{ local_tmp_dir }}/{{ app_name }}-{{ app_version }}.tar.gz"
    flat: yes
  delegate_to: "{{ groups[build_host][0] }}"
  remote_user: "{{ build_user }}"

- name: Upload release
  copy:
    src: "{{ local_tmp_dir }}/{{ app_name }}-{{ app_version }}.tar.gz"
    dest: "{{ upload_path }}"
