---

- name: Fetch release
  fetch:
    src: "{{ project_path }}/rel/{{ app_name }}/releases/{{ app_version }}/{{ app_name }}.tar.gz"
    dest: "{{ local_tmp_dir }}/{{ app_name }}-{{ app_version }}.tar.gz"
    flat: yes
  delegate_to: "{{ build_server }}"
  become: false
  remote_user: "{{ build_user }}"

- name: Upload release
  copy:
    src: "{{ local_tmp_dir }}/{{ app_name }}-{{ app_version }}.tar.gz"
    dest: "{{ upload_path }}"
  become: true
  become_user: "{{ user }}"
