---

- name: Install hex
  command: mix local.hex --force
  delegate_to: "{{ groups[build_host][0] }}"
  remote_user: "{{ build_user }}"

- name: Install rebar
  command: mix local.rebar
  delegate_to: "{{ groups[build_host][0] }}"
  remote_user: "{{ build_user }}"
